movie_app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class NewPost(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])

    content = TextAreaField('Content', validators=[DataRequired()])

    submit = SubmitField('Submit')

movie_app/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from movie_app import db
from movie_app.models import Post
from movie_app.posts.forms import NewPost

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def n_post():
    form = NewPost()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post was successful!', 'success')
        return redirect(url_for('main.home'))
    return render_template('post_creation.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def posty(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = NewPost()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post was updated successfully!', 'success')
        return redirect(url_for('posts.posty', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('post_creation.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def deletePost(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted successfully!', 'success')
    return redirect(url_for('main.home'))

movie_app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from movie_app import db, bcrypt
from movie_app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, PassowrdReset, ResetForm
from movie_app.models import User, Post
from flask_login import login_user, current_user, logout_user, login_required
from movie_app.users.utils import save_pic, send_email

users = Blueprint('users', __name__)
#registration page
@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user. is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

#Login page
@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user. is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.layout'))
        else:
            flash('Login failed', 'danger')
    return render_template('login.html', title='Login', form=form)

#user logout function
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.layout'))

#account page
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_pic(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method =='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='images/' + current_user.image_file)
    return render_template('acc.html', title='Account', image_file=image_file, form=form)

#user's personal posts
@users.route("/user/<string:username>")
def users_stuff(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('user_stuff.html', posts=posts, user=user)

#password request page
@users.route("/password_reset", methods=['GET', 'POST'])
def request_reset():
    if current_user. is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_email(user)
        flash('Reset email has been sent', 'info')
        return redirect(url_for('users.login'))
    return render_template('request_reset.html', title='Password Reset', form=form)

#password reset page
@users.route("/password_reset/<token>", methods=['GET', 'POST'])
def token_request(token):
    if current_user. is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_token(token)
    if user is None:
        flash('Token has expired', 'warning')
        return redirect(url_for('main.equest_reset'))
    form = PassowrdReset()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password was reset successfully', 'success')
        return redirect(url_for('users.login'))
    return render_template('token_request.html', title='Password Reset', form=form )

movie_app/templates/about.html
{% extends "layout.html" %}

{% block content %}


<h1 id="about_us" class="font-effect-3d"><u>About us</u></h1>

<body>


<div id="about">
<i>It doesn’t matter what model you drive. Whether you’re driving your first Bimmer, or your thirtieth,
there are just certain subjects that interest only BMW owners. BMW CCA is where we explore all of
them; it is where we fuel our passion for the marque with friendship, family and fun!
Our official mission is: to enhance the BMW experience for our members by providing services, support,
information, and activities that promote camaraderie and encourage social awareness and
responsibility. Unofficially, we’re a big support group for the Ultimate Driving Machine addiction.
At the heart of our values is the promotion of motoring citizenship, lifelong driving skills and
social responsibility. We live those values by actively supporting the BMW Car Club of America
Foundation and its Tire Rack Street Survival Program.</i>

<br><p></p>

<i>With over 1.3 million part numbers in our catalog and a modern facility, Swapportunities is a truly
unique company. An active and fully engaged management team closely monitors all business
functions. The early business plan remains, with refinements based on statistical analysis
of daily operations and customer feedback.

All operations are handled in house. Everything. Web design and programming, marketing
and photography, inventory management and shipping, product applications, customer service
and tech support, and research and development tasks are all performed by Swapportunities employees.

As we move deeper into the 21st century, we cling to old values, remembering our roots,
even as we embrace change.

That's why we still answer the phone, an increasingly rare service in a world of
automated phone-bots (which would be cheaper for us, but a lot more aggravating for you).
Our skilled and pleasant live support staff is ready to assist you from 8:00 a.m. to
11 p.m. EST (Monday - Friday) and 10:00 a.m. to 7:00 p.m. EST (Saturday).

That's why we tweak and polish the web site interface to improve navigation, and streamline
the ordering process.
</i></div>

<div class="clearfix">
  <div class="img-container">
    <img id="ecs" src="/static/images/ECS-Tuning-850x500.jpg" style="width:85%">
  </div>
</div>

</body>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/acc.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
      <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>

        <form method="POST" action="" enctype="multipart/form-data">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend id="join" class="font-effect-3d"><h1>Account Info</h1></legend>
                  <div class="form-group">
                      {{ form.username.label(class="form-control-label") }}

                      {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.email.label(class="form-control-label") }}

                      {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.picture.label() }}
                      {{ form.picture(cass= "form-control-file") }}
                      {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                      <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                      {% endif %}
                  </div>
              </fieldset>
            <div id="butt" class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/cart.html
{% extends "layout.html" %}

{% block content %}

<h1 id="cus"><u>Contact Us</u></h1>

<article id="tings">
<div>
<p id="cuss">Wolverine – Alexis Hennings – Owner & Administrator
    Spiderman – Peter Parker –  Administrator</p>

<p> For more information about advertising, please contact us at db7vantage007@gmail.com or visit our Advertising Page
    Swapportunities.com is an enthusiast website with message board that was started in late 2000. Members get to know
    each other online, but many also meet in person at different times during the year at special events. We are not
    associated with, or financially supported by, BMW. The site is free to all non-commercial members.
    Swapportunities.com is a website dedicated to owners and enthusiasts of BMW automobiles. We invite you to browse
    around and see the vast amount of information that is available to you here.
    Be sure to take a look at our forum-style message board where thousands of members discuss BMW related topics
    around the clock! Our message board is the heart of Swapportunities.com with a huge following of members that grows
    daily. If you like to share and exchange information and ideas about BMW related topics, this is the place for you!
    If you prefer to just lurk and learn we love to have visitors too! If you like what you see (and we know you will)
    register as a member and say hello to our large and friendly BMW community. It’s free, it’s enlightening, it’s
    informative and it’s fun! We want you to experience what thousands of members “already” enjoy on Swapportunities.com.
    Come join us! </p>
</div>
</article>
<!-- stripe credit card payment -->
  <div class="pay">
    <form action="your-server-side-code" method="POST">
      <script
        src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="pk_test_TYooMQauvdEDq54NiTphI7jx"
        data-amount="999"
        data-name="Stripe.com"
        data-description="Example charge"
        data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
        data-locale="auto"
        data-zip-code="true">
      </script>
    </form>
  </div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/home.html
{% extends "layout.html" %}

{% block content %}

{% for post in posts.items %}
    <article id="ting" class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.users_stuff', username=post.author.username) }}">
                    {{ post.author.username }}
                </a>
                <small class="text-muted">
                    {{ post.date_posted.strftime('%Y-%m-%d') }}
                </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.posty', post_id=post.id) }}">
                {{ post.title }}
            </a></h2>
            <p id="juliet" class="article-content">
                {{ post.content }}
            </p>
        </div>
    </article>
{% endfor %}

<p id="meets">Monthly car meet will be held at:</p>
<p id="meet">1100 Canterbury Rd S, Shakopee, MN 55379</p>
<div class="maps" id="map">

    <!-- Google map location for car show -->
    <script type='text/javascript'>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 44.786, lng: -93.480},
          zoom: 15
        });
      }
    </script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyClny7Vks-NEUXEMvhqhqPUjOYySMzW16k&callback=initMap"
    async defer></script>

    <!-- confirmation pop up for logout -->
    <script type='text/javascript'>

        function confirmLogout(){
            var agree = confirm("Are you sure you want to logout?");

            if(agree){
                return true;

                }else{

                return false;
            }
        }
    </script>

</div>

{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
       {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
     {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
     {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}
{% endblock content %}

movie_app/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div id="reg" class="content-section">
        <form id="cake" method="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend id="join" class="font-effect-3d"><h1>Log In</h1></legend>

                  <div class="form-group">
                      {{ form.email.label(class="form-control-label") }}

                      {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.password.label(class="form-control-label") }}

                      {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-check">
                      {{ form.remember(class="form-check-input") }}
                      {{ form.remember.label(class="form-check-label") }}
                  </div>
              </fieldset>
            <div id="butt" class="form-group"></div>
            <div>
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a id="forgot" href="{{ url_for('users.request_reset') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
<div id="sign">
    <small id="signs" class="text-muted">
        New to Swapportunities? <a class="ml-2" href="{{ url_for('users.register') }}">Sign up now</a>
    </small>
</div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/post.html
{% extends "layout.html" %}

{% block content %}

    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
        <div  class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.users_stuff', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.post_update', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
                {% endif %}
            </div>
            <h2 id="cop" class="article-title">{{ post.title }}</h2>
            <p id="cops" class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Delete Post</h5>

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{ url_for('posts.deletePost', post_id=post.id) }}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/post_creation.html
{% extends "layout.html" %}

{% block content %}
<div id="reg" class="content-section">
        <form method="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend id="join" class="font-effect-3d"><h1>{{ legend }}</h1></legend>

                  <div class="form-group">
                      {{ form.title.label(class="form-control-label") }}
                      {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.content.label(class="form-control-label") }}
                      {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
              </fieldset>
            <div id="butt" class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/products.html
{% extends "layout.html" %}

{% block content %}
<!-- parts/products page -->
<div id="laugh">
  <h3 class="font-effect-fire-animation" id="fire">Fire Sale Item!</h3>
    <img src="/static/images/m3kit.png" id="m3kit">
    <h3 id="meg">M3 Replica Bodykit</h3>
    <h4 id="megs">Price: $599.99</h4><p>%10 off <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Add</button></p>
</div>

<div id="cry">
    <img src="/static/images/vvti-2jz-supra-engine-for-sale2.jpg" id="m3kits">
    <h3 id="lois">Inline 6 VVTi 2JZ</h3>
    <h4 id="louis">Price: $2,599.99</h4>
    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Add</button>
</div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div id="reg" class="content-section">
        <form method="POST" action="">
              {{ form.hidden_tag() }}
              <fieldset class="form-group">
                  <legend id="join" class="font-effect-3d"><h1>Join Today!</h1></legend>
                  <div class="form-group">
                      {{ form.username.label(class="form-control-label") }}

                      {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.email.label(class="form-control-label") }}

                      {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.password.label(class="form-control-label") }}

                      {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
                  <div class="form-group">
                      {{ form.confirm_password.label(class="form-control-label") }}

                      {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                      {% endif %}
                  </div>
              </fieldset>
            <div id="butt" class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
<div id="sign" class="border-top pt-3">
    <small id="signs" class="text-muted">
        Already have an account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign in</a>
    </small>
</div>

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}

movie_app/templates/user_stuff.html
{% extends "layout.html" %}

{% block content %}

<h1 class="mb-3"><u>{{ user.username }}'s Posts ({{ posts.total }})</u></h1>

{% for post in posts.items %}
    <article id="yeti" class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='images/' + post.author.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.users_stuff', username=post.author.username) }}">
                    {{ post.author.username }}
                </a>
                <small class="text-muted">
                    {{ post.date_posted.strftime('%Y-%m-%d') }}
                </small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.posty', post_id=post.id) }}">
                {{ post.title }}
            </a></h2>
            <p id="lassie" class="article-content">
                {{ post.content }}
            </p>
        </div>
    </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
       {% if posts.page == page_num %}
        <a class="btn btn-info mb-4" href="{{ url_for('users.users_stuff', username=user.username, page=page_num) }}">{{ page_num }}</a>
     {% else %}
        <a class="btn btn-outline-info mb-4" href="{{ url_for('users.users_stuff', username=user.username, page=page_num) }}">{{ page_num }}</a>
     {% endif %}
    {% else %}
        ...
    {% endif %}
{% endfor %}

<!-- confirmation pop up for logout -->
<script type='text/javascript'>

    function confirmLogout(){
        var agree = confirm("Are you sure you want to logout?");

        if(agree){
            return true;

            }else{

            return false;
        }
    }
</script>

{% endblock content %}